(function(){
var $=function(s){return document.querySelector(s)}, $$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
var vals=[100,200,300,500,1000,2000,4000,8000,16000,32000,64000,125000,250000,500000,1000000], letters=['A','B','C','D'];
var S={name:'Player',i:0,qs:[],sel:null,locked:false,next:false,t:45,tid:null,pause:false,used:{fifty:0,audience:0,friend:0,switch:0},mute:false,end:false};
var audio=null;
function tone(f,d,type,g,delay){if(S.mute)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();var o=audio.createOscillator(),v=audio.createGain(),n=audio.currentTime+(delay||0);o.type=type||'sine';o.frequency.value=f;v.gain.setValueAtTime(.0001,n);v.gain.exponentialRampToValueAtTime(g||.04,n+.01);v.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(v);v.connect(audio.destination);o.start(n);o.stop(n+d+.03)}catch(e){}}
function sfx(k){if(k==='pick')tone(520,.08,'triangle');if(k==='lock'){tone(280,.3);tone(430,.25,'triangle',.025,.1)}if(k==='ok'){tone(523,.15,'triangle');tone(659,.18,'triangle',.04,.12);tone(784,.3,'triangle',.04,.25)}if(k==='bad'){tone(170,.45,'sawtooth',.025);tone(125,.5,'sawtooth',.018,.1)}if(k==='life'){tone(880,.12);tone(1100,.18,'sine',.03,.1)}}
function show(id){$$('.screen').forEach(function(x){x.classList.toggle('active',x.id===id)});close()}
function shuffle(a){a=a.slice();for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=a[i];a[i]=a[j];a[j]=t}return a}
function diff(i){return i<5?'easy':i<10?'medium':i<13?'hard':'jackpot'}
function fmt(n){return Number(n).toLocaleString('en-IN')}
function makeQs(){S.qs=[];var used={};for(var i=0;i<15;i++){var p=shuffle(Q.filter(function(q){return q.d===diff(i)&&!used[q.id]}));var q=p[0];used[q.id]=1;S.qs.push(q)}}
function ladder(){var e=$('#ladder');e.innerHTML='';vals.forEach(function(v,i){var li=document.createElement('li');if(i===4||i===9)li.className='safe';li.innerHTML='<span>'+(i+1)+'</span><b>'+fmt(v)+'</b><span></span>';e.appendChild(li)});ladderState()}
function ladderState(){$$('#ladder li').forEach(function(x,i){x.classList.toggle('current',i===S.i&&!S.end);x.classList.toggle('passed',i<S.i)})}
function reset(){S.i=0;S.sel=null;S.locked=false;S.next=false;S.pause=false;S.end=false;S.used={fifty:0,audience:0,friend:0,switch:0};makeQs();ladder();$('#player').textContent=S.name.toUpperCase();$$('.lifelines button').forEach(function(b){b.classList.remove('used');b.disabled=false})}
function render(){clearInterval(S.tid);var q=S.qs[S.i];if(!q)return finish(1);S.sel=null;S.locked=false;S.next=false;S.pause=false;$('#qno').textContent='QUESTION '+(S.i+1);$('#cat').textContent=S.i>=9?'THE HOT SEAT':q.c.toUpperCase();$('#value').textContent=fmt(vals[S.i]);$('#score').textContent=S.i?fmt(vals[S.i-1]):'0';$('#question').textContent=q.q;$('#prompt').textContent='Choose A, B, C or D';$('#explain').classList.remove('show');$('#explain').textContent='';$('#lock').disabled=true;$('#lock').textContent='LOCK ANSWER';var a=$('#answers');a.innerHTML='';q.o.forEach(function(o,i){var b=document.createElement('button');b.className='answer';b.dataset.i=i;b.innerHTML='<span class="letter">'+letters[i]+'</span><span>'+o+'</span>';b.onclick=function(){pick(i)};a.appendChild(b)});ladderState();startTimer()}
function pick(i){if(S.locked||S.next)return;var b=$('.answer[data-i="'+i+'"]');if(!b||b.classList.contains('hide'))return;S.sel=i;sfx('pick');$$('.answer').forEach(function(x,j){x.classList.toggle('sel',j===i)});$('#prompt').textContent=letters[i]+' selected';$('#lock').disabled=false}
function lock(){if(S.next){next();return}if(S.sel===null||S.locked)return;S.locked=true;clearInterval(S.tid);var q=S.qs[S.i],b=$('.answer[data-i="'+S.sel+'"]');$('#lock').disabled=true;$('#lock').textContent='LOCKED IN';$$('.answer').forEach(function(x){x.disabled=true});sfx('lock');setTimeout(function(){var c=$('.answer[data-i="'+q.a+'"]');c.classList.add('correct');$('#explain').textContent='✦ '+q.e;$('#explain').classList.add('show');if(S.sel===q.a){sfx('ok');$('#prompt').textContent='Correct answer';S.next=true;if(S.i===14)setTimeout(function(){finish(1)},1800);else setTimeout(function(){$('#lock').disabled=false;$('#lock').textContent='NEXT QUESTION'},700)}else{b.classList.add('wrong');sfx('bad');$('#prompt').textContent='That was not the answer';setTimeout(function(){finish(0)},2200)}},900)}
function next(){if(!S.next)return;S.i++;render()}
function startTimer(){S.t=45;clock();S.tid=setInterval(function(){if(S.pause)return;S.t--;clock();if(S.t<=0){clearInterval(S.tid);var q=S.qs[S.i];$$('.answer').forEach(function(x){x.disabled=true});$('.answer[data-i="'+q.a+'"]').classList.add('correct');$('#explain').textContent='✦ '+q.e;$('#explain').classList.add('show');sfx('bad');setTimeout(function(){finish(0)},1900)}},1000)}
function clock(){$('#time').textContent=S.t;$('#ring').style.strokeDashoffset=113.1*(1-S.t/45);$('#ring').style.stroke=S.t<=10?'var(--red)':'var(--gold)'}
function life(k){if(S.used[k]||S.locked||S.next)return;S.used[k]=1;var btn=$('[data-life="'+k+'"]');btn.classList.add('used');btn.disabled=true;sfx('life');if(k==='fifty'){var q=S.qs[S.i],w=shuffle([0,1,2,3].filter(function(i){return i!==q.a})).slice(0,2);w.forEach(function(i){$('.answer[data-i="'+i+'"]').classList.add('hide')})}if(k==='audience')audience();if(k==='friend')open('friendModal');if(k==='switch')switchQ()}
function audience(){var q=S.qs[S.i],p=[0,0,0,0],right=44+Math.floor(Math.random()*24),r=100-right,w=[0,1,2,3].filter(function(i){return i!==q.a});p[q.a]=right;for(var x=0;x<2;x++){var n=Math.floor(Math.random()*(r+1));p[w[x]]=n;r-=n}p[w[2]]=r;var e=$('#bars');e.innerHTML='';p.forEach(function(n,i){e.innerHTML+='<div class="bar"><b>'+n+'%</b><div class="track"><i class="fill" data-h="'+n+'"></i></div><strong>'+letters[i]+'</strong></div>'});open('audienceModal');setTimeout(function(){$$('.fill').forEach(function(x){x.style.height=x.dataset.h+'%'})},60)}
function switchQ(){var d=diff(S.i),p=shuffle(Q.filter(function(q){return q.d===d&&!S.qs.some(function(x){return x.id===q.id})}));if(p.length){S.qs[S.i]=p[0];render()}}
var callId;function friend(){var n=30;$('#friendTime').textContent=n;$('#friendStart').disabled=true;clearInterval(callId);callId=setInterval(function(){n--;$('#friendTime').textContent=n;if(n<=0){clearInterval(callId);$('#friendStart').disabled=false;$('#friendStart').textContent='TIME IS UP';tone(220,.5);setTimeout(function(){$('#friendStart').textContent='START 30 SECONDS'},1000)}},1000)}
function floor(){return S.i>=10?32000:S.i>=5?1000:0}
function finish(win){clearInterval(S.tid);S.end=true;var sc=win?vals[Math.min(S.i,14)]:floor(),v=$('#victory');save(sc,win);$('#rn').textContent=S.name.toUpperCase();$('#rs').textContent=fmt(sc);$('#rk').textContent=win?'NAVRATRI CHAMPION':'WHAT A RUN';$('#rc').textContent=win?'You conquered the Hot Seat with':'You leave the Hot Seat with';v.classList.toggle('show',!!win);if(win){v.currentTime=0;v.play().catch(function(){})}else v.pause();show('result');confetti(win?220:70);if(win)sfx('ok')}
function getBoard(){try{return JSON.parse(localStorage.getItem('navquiz-board'))||[]}catch(e){return[]}}
function save(sc,win){var b=getBoard();b.push({n:S.name,s:sc,w:win,t:Date.now()});b.sort(function(a,b){return b.s-a.s||a.t-b.t});localStorage.setItem('navquiz-board',JSON.stringify(b.slice(0,20)))}
function board(){var b=getBoard(),e=$('#board');e.innerHTML=b.length?'':'<p class="muted">No contestants yet.</p>';b.forEach(function(r,i){var d=document.createElement('div');d.className='row';d.innerHTML='<b>'+(i+1)+'</b><span><strong></strong><small> '+(r.w?'Champion':'Contestant')+'</small></span><b>'+fmt(r.s)+'</b>';d.querySelector('strong').textContent=r.n;e.appendChild(d)})}
function open(id){$('#'+id).classList.add('open')}function close(){$$('.modal').forEach(function(m){m.classList.remove('open')})}
function fullscreen(){if(!document.fullscreenElement)document.documentElement.requestFullscreen().catch(function(){});else document.exitFullscreen().catch(function(){})}
function intro(){show('intro');$('#introName').textContent=S.name.toUpperCase();var n=3;$('#count').textContent=n;var id=setInterval(function(){n--;if(n){$('#count').textContent=n;tone(300+n*100,.12)}else{clearInterval(id);$('#count').textContent='GO';tone(720,.3,'triangle');setTimeout(function(){show('game');render()},500)}},800);$('#skip').onclick=function(){clearInterval(id);show('game');render()}}
function confetti(num){var c=$('#fx'),x=c.getContext('2d');c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.scale(devicePixelRatio,devicePixelRatio);var col=['#f6c66a','#ff7a2f','#ff2f8f','#7944ff','#38d98b'],a=[];for(var i=0;i<num;i++)a.push({x:Math.random()*innerWidth,y:-30-Math.random()*innerHeight*.4,vx:(Math.random()-.5)*5,vy:2+Math.random()*5,r:2+Math.random()*5,c:col[i%col.length]});var f=0;(function draw(){x.clearRect(0,0,innerWidth,innerHeight);a.forEach(function(p){p.x+=p.vx;p.y+=p.vy;p.vy+=.025;x.fillStyle=p.c;x.fillRect(p.x,p.y,p.r*2,p.r)});if(f++<220)requestAnimationFrame(draw)})()}
$('#enter').onclick=function(){show('setup');setTimeout(function(){$('#name').focus()},100)};$('#start').onclick=function(){S.name=$('#name').value.trim()||'Player';reset();intro()};$('#name').onkeydown=function(e){if(e.key==='Enter')$('#start').click()};$$('[data-go]').forEach(function(b){b.onclick=function(){show(b.dataset.go)}});$('#lock').onclick=lock;$$('[data-life]').forEach(function(b){b.onclick=function(){life(b.dataset.life)}});$$('.x').forEach(function(b){b.onclick=close});$$('.boardBtn').forEach(function(b){b.onclick=function(){board();open('boardModal')}});$('#clear').onclick=function(){localStorage.removeItem('navquiz-board');board()};$('#friendStart').onclick=friend;$('#again').onclick=function(){$('#name').value='';show('setup')};$('#sound').onclick=function(){S.mute=!S.mute;this.textContent=S.mute?'×':'♪'};$('#full').onclick=fullscreen;$('#home').onclick=function(){clearInterval(S.tid);show('landing')};$('#pause').onclick=function(){S.pause=!S.pause;this.childNodes[0].nodeValue=S.pause?'RESUME TIMER ':'PAUSE TIMER '};$('#reveal').onclick=function(){if(!S.locked&&!S.next){S.sel=S.qs[S.i].a;lock()}};$('#next').onclick=next;$('#hostFull').onclick=fullscreen;document.onkeydown=function(e){if(e.target.tagName==='INPUT')return;var k=e.key.toLowerCase();if(e.key>='1'&&e.key<='4')pick(Number(e.key)-1);else if(e.key==='Enter')lock();else if(e.code==='Space'){e.preventDefault();next()}else if(k==='h')open('hostModal');else if(k==='m')$('#sound').click();else if(k==='p')S.pause=!S.pause;else if(k==='r')$('#reveal').click();else if(e.key==='Escape')close()};ladder();
})();