window.Q=[
['easy','Navratri','How many nights are traditionally celebrated during Navratri?',['7','8','9','10'],2,'Navratri literally refers to nine nights of celebration.'],
['easy','Navratri','Garba is most strongly associated with which Indian state?',['Punjab','Gujarat','Kerala','Odisha'],1,'Garba is a traditional dance form closely associated with Gujarat.'],
['easy','India','Which city is home to the Taj Mahal?',['Jaipur','Agra','Lucknow','Delhi'],1,'The Taj Mahal stands in Agra, Uttar Pradesh.'],
['easy','World','What is the capital of Japan?',['Seoul','Kyoto','Tokyo','Osaka'],2,'Tokyo is the capital of Japan.'],
['easy','Science','Which is the largest planet in our solar system?',['Earth','Saturn','Jupiter','Neptune'],2,'Jupiter is the largest planet in our solar system.'],
['easy','Sports','How many overs does each side normally receive in a T20 cricket innings?',['10','20','25','50'],1,'Twenty20 cricket gives each side a maximum of 20 overs.'],
['easy','Food','Paneer is traditionally made from what?',['Milk','Rice','Lentils','Wheat'],0,'Paneer is a fresh cheese made from milk.'],
['easy','Bollywood','Who played Rancho in the film “3 Idiots”?',['Shah Rukh Khan','Aamir Khan','Ranbir Kapoor','Hrithik Roshan'],1,'Aamir Khan played Rancho in “3 Idiots”.'],
['easy','Brain Teaser','If you have 3 apples and take away 2, how many apples do you have?',['1','2','3','5'],1,'You took two apples, so you have those two.'],
['easy','India','What is the currency of India?',['Rupee','Taka','Rial','Baht'],0,'India uses the Indian rupee.'],
['easy','World','Which ocean lies between Africa and Australia?',['Atlantic','Indian','Arctic','Southern'],1,'The Indian Ocean lies between Africa and Australia.'],
['easy','Science','What is H₂O commonly called?',['Hydrogen','Oxygen','Water','Salt'],2,'H₂O is the chemical formula for water.'],
['medium','Navratri','The word “Navratri” most directly translates to what?',['Nine nights','Sacred dance','Festival lights','Victory day'],0,'“Nav” means nine and “ratri” means night.'],
['medium','Festivals','Mysuru Dasara is especially associated with which state?',['Karnataka','Rajasthan','Bihar','Goa'],0,'Mysuru Dasara is a major celebration in Karnataka.'],
['medium','India','Kaziranga National Park is in which state?',['Assam','Sikkim','Jharkhand','Uttarakhand'],0,'Kaziranga National Park is in Assam.'],
['medium','India','Where is ISRO headquartered?',['Hyderabad','Mumbai','Bengaluru','Chennai'],2,'ISRO is headquartered in Bengaluru.'],
['medium','Science','What is the chemical symbol for iron?',['Ir','Fe','In','I'],1,'Iron uses the symbol Fe, from the Latin ferrum.'],
['medium','World','The ancient city of Petra is in which modern country?',['Jordan','Egypt','Greece','Turkey'],0,'Petra is an archaeological city in Jordan.'],
['medium','Sports','Under standard rally scoring, how many points normally win a badminton game?',['15','18','21','25'],2,'A badminton game is normally played to 21 points.'],
['medium','Brain Teaser','What comes next: 2, 3, 5, 8, 13, 21, …?',['29','31','34','36'],2,'Each number is the sum of the previous two, so 34 comes next.'],
['medium','Music','Which Indian composer won Academy Awards for “Slumdog Millionaire”?',['A. R. Rahman','Ilaiyaraaja','Pritam','Shankar Mahadevan'],0,'A. R. Rahman won two Academy Awards for the film.'],
['medium','Food','Which pulse is traditionally fermented with rice to make classic idli batter?',['Urad dal','Chana dal','Masoor dal','Moong dal'],0,'Traditional idli batter combines rice with urad dal.'],
['medium','India','Which river flows through Varanasi?',['Yamuna','Narmada','Ganga','Godavari'],2,'Varanasi stands on the banks of the Ganga.'],
['medium','Bollywood','Which film features the characters Geet and Aditya?',['Jab We Met','Tamasha','Barfi!','Rockstar'],0,'Geet and Aditya are the central characters of “Jab We Met”.'],
['hard','Navratri','What collective name is commonly used for the nine forms of Goddess Durga worshipped across Navratri?',['Navadurga','Dashavatara','Ashtalakshmi','Saptamatrika'],0,'The nine forms are collectively known as Navadurga.'],
['hard','Navratri','Which form of Durga is traditionally worshipped on the first day of Sharad Navratri?',['Kalaratri','Shailaputri','Siddhidatri','Mahagauri'],1,'Shailaputri is traditionally worshipped on the first day.'],
['hard','India','How many Indian states does the Tropic of Cancer pass through?',['6','7','8','9'],2,'The Tropic of Cancer passes through eight Indian states.'],
['hard','India','Which Indian state has the longest coastline?',['Andhra Pradesh','Tamil Nadu','Gujarat','Maharashtra'],2,'Gujarat has the longest coastline among Indian states.'],
['hard','Culture','Bathukamma is a floral festival primarily associated with which state?',['Telangana','Punjab','Goa','Assam'],0,'Bathukamma is a major floral festival of Telangana.'],
['hard','Culture','Mohiniyattam is a classical dance form from which state?',['Kerala','Odisha','Manipur','Gujarat'],0,'Mohiniyattam originated in Kerala.'],
['hard','Science','Which element has the chemical symbol W?',['Tungsten','Tin','Tantalum','Titanium'],0,'W is the symbol for tungsten, from its older name wolfram.'],
['hard','Maths','Which number is famously known as the Hardy–Ramanujan number?',['1089','1729','2048','4104'],1,'1729 is the famous Hardy–Ramanujan number.'],
['hard','World','Machu Picchu was built by which civilisation?',['Maya','Aztec','Inca','Olmec'],2,'Machu Picchu was built by the Inca civilisation.'],
['hard','India','The Sundarbans National Park is located in which Indian state?',['West Bengal','Odisha','Assam','Kerala'],0,'The Indian Sundarbans are in West Bengal.'],
['jackpot','Culture','Garba of Gujarat was inscribed on UNESCO’s Representative List of Intangible Cultural Heritage in which year?',['2019','2021','2023','2025'],2,'UNESCO inscribed Garba of Gujarat on the list in 2023.'],
['jackpot','India','Which is the smallest Indian state by area?',['Sikkim','Tripura','Goa','Manipur'],2,'Goa is India’s smallest state by area.'],
['jackpot','Science','Which scientist formulated the three laws of planetary motion?',['Galileo Galilei','Johannes Kepler','Isaac Newton','Tycho Brahe'],1,'Johannes Kepler formulated the three laws of planetary motion.'],
['jackpot','World','Which strait separates Asia from North America?',['Bosporus','Bering Strait','Strait of Malacca','Gibraltar'],1,'The Bering Strait separates Asia from North America.'],
['jackpot','Maths','A regular dodecagon has how many diagonals?',['44','48','54','60'],2,'A 12-sided polygon has 12×9÷2 = 54 diagonals.'],
['jackpot','Science','What is the SI unit of electric capacitance?',['Weber','Farad','Tesla','Henry'],1,'Capacitance is measured in farads.'],
['jackpot','Culture','Which text is traditionally attributed to Bharata Muni and discusses drama, dance and performance?',['Arthashastra','Natya Shastra','Yoga Sutras','Panchatantra'],1,'The Natya Shastra is traditionally attributed to Bharata Muni.']
].map(function(x,i){return{d:x[0],c:x[1],q:x[2],o:x[3],a:x[4],e:x[5],id:i}});